export const shopCategories = [
  { label: "Accessories", value: "accessories" },
  { label: "Art & Collectibles", value: "art-collectibles" },
  { label: "Baby & Kids", value: "baby-kids" },
  { label: "Beauty & Personal Care", value: "beauty-personal-care" },
  { label: "Books", value: "books" },
  { label: "Clothing", value: "clothing" },
  { label: "Electronics", value: "electronics" },
  { label: "Food & Beverage", value: "food-beverage" },
  { label: "Furniture & Home Decor", value: "furniture-home-decor" },
  { label: "Gaming", value: "gaming" },
  { label: "Gifts", value: "gifts" },
  { label: "Health & Wellness", value: "health-wellness" },
  { label: "Home & Garden", value: "home-garden" },
  { label: "Jewelry", value: "jewelry" },
  { label: "Kitchen & Dining", value: "kitchen-dining" },
  { label: "Music", value: "music" },
  { label: "Office Supplies", value: "office-supplies" },
  { label: "Outdoor & Sports", value: "outdoor-sports" },
  { label: "Pet Supplies", value: "pet-supplies" },
  { label: "Shoes", value: "shoes" },
  { label: "Sports", value: "sports" },
  { label: "Toys & Games", value: "toys-games" },
  { label: "Travel", value: "travel" },
  { label: "Vintage", value: "vintage" },
];
